### ISSUE TITLE
`array_copy` is unsafe

### ISSUE THREAD

**Issue by fluffywaffles** [fluffywaffles/prettybad-util#1]
Often get these irritating exceptions that say something like:

```
TypeError: Cannot redefine property: length
    at defineProperty (<anonymous>)
    at o (/home/fluffywaffles/dev/μtil/out.js:24:46)
    at /home/fluffywaffles/dev/μtil/out.js:123:38
    at Array.reduce (<anonymous>)
    at arr (/home/fluffywaffles/dev/μtil/out.js:143:47)
    at b (/home/fluffywaffles/dev/μtil/out.js:334:36)
    at Object.array_copy (/home/fluffywaffles/dev/μtil/out.js:553:42)
```

Well, that's because `array_copy` doesn't check its arguments.

This would also be solved by writing polymorphic `copy` and guarding invocations with `instanceof` checks. But that moreso *hides* the bug, rather than removing it. Better to check the argument to `array_copy` itself.

Thiiiiis would also not be an issue if we had (at least *some*) types.

**Comment by fluffywaffles** [comment]
Does `Array.from` perform a safe copy?

**Comment by fluffywaffles** [comment]
It does... but it will return empty array for weird inputs.

```
Array.from({}) // =>  []
Array.from(function () {}) // => []
Array.from(mu.None) // => []
Array.from(NaN) // => []
Array.from(123) // => []
Array.from(undefined) // => exception
Array.from(null) // => exception
```

**Comment by fluffywaffles** [comment]
Used `concat`. It's faster. `define.mut` is slow, as it turns out -- really slow. `Array.from` was still showing up in flamegraphs. So not `array_copy` just defers to `concat`.
